management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: nacos-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#      config:
#        file-extension: yml
#        server-addr: localhost:8848
#        prefix: test
server:
  port: 3002